name: Deploy API Image to GHCR

on:
  workflow_dispatch:

jobs:
  push-store-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@main

      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@main
        with:
          android: true # 12gb
          dotnet: true # 3.9gb
          haskell: true # 6.2gb
          large-packages: false # 4.7gb, takes a lot of time
          docker-images: false
          swap-storage: false
          # this might remove tools that are actually needed, but frees about 6 GB
          tool-cache: false

      - name: 'Build Image'
        run: |
          docker build . --tag ghcr.io/manuel-materazzo/battista-ai-backend:latest
          docker push ghcr.io/manuel-materazzo/battista-ai-backend:latest
